on: 
  push: 
    branches: 
      - master 
      - develop 

name: Deploy and Slack Notification
jobs:
  deploy:
    name: Deploy
    # Change below line to: `runs-on: ubuntu-latest` if not using self-hosted runners or if it is a public repo.
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      uses: rtCamp/action-deploy-wordpress@master
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        WP_VERSION: 5.4.2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: test
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
